[build]
buildCommand = "npm run build && npm install --include=dev --prefix backend"

[deploy]
startCommand = "cd backend && npx tsx src/server.ts"
buildCommand = "npm run build"
healthcheckUrl = "/health"
